// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_duplicates_int
std::vector<int> C_duplicates_int(std::vector<int> x);
RcppExport SEXP _salixUtils_C_duplicates_int(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_duplicates_int(x));
    return rcpp_result_gen;
END_RCPP
}
// C_duplicates_dbl
std::vector<double> C_duplicates_dbl(std::vector<double> x);
RcppExport SEXP _salixUtils_C_duplicates_dbl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_duplicates_dbl(x));
    return rcpp_result_gen;
END_RCPP
}
// C_duplicates_log
std::vector<bool> C_duplicates_log(std::vector<bool> x);
RcppExport SEXP _salixUtils_C_duplicates_log(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<bool> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_duplicates_log(x));
    return rcpp_result_gen;
END_RCPP
}
// C_duplicates_char
std::vector<std::string> C_duplicates_char(std::vector<std::string> x);
RcppExport SEXP _salixUtils_C_duplicates_char(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_duplicates_char(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_salixUtils_C_duplicates_int", (DL_FUNC) &_salixUtils_C_duplicates_int, 1},
    {"_salixUtils_C_duplicates_dbl", (DL_FUNC) &_salixUtils_C_duplicates_dbl, 1},
    {"_salixUtils_C_duplicates_log", (DL_FUNC) &_salixUtils_C_duplicates_log, 1},
    {"_salixUtils_C_duplicates_char", (DL_FUNC) &_salixUtils_C_duplicates_char, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_salixUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
