# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_duplicates_int <- function(x) {
    .Call(`_salixUtils_C_duplicates_int`, x)
}

C_duplicates_dbl <- function(x) {
    .Call(`_salixUtils_C_duplicates_dbl`, x)
}

C_duplicates_log <- function(x) {
    .Call(`_salixUtils_C_duplicates_log`, x)
}

C_duplicates_char <- function(x) {
    .Call(`_salixUtils_C_duplicates_char`, x)
}

